### ISSUE TITLE
Update on 2.0.8 ?

### ISSUE THREAD

**Issue by waghanza** [theAkito/docker-nim#1]
Hi @theAkito,

Thanks for this project, I cqn now use nim on arm64.

However, 2.0.8 is out today, at least tag is created on https://github.com/nim-lang/Nim.

Maybe a good idea to jump from 2.0.4 to 2.0.8.

Regards,

**Comment by theAkito** [comment]
I'm glad you are enjoying the project! 🙂



> Maybe a good idea to jump from 2.0.4 to 2.0.8.

Indeed. I already thought about having an automation process for this, so I don't have to always bump manually, but I didn't get to it, yet.

**Comment by theAkito** [comment]
Done with e0f255785e14f3729082ac90947b06168747fb95.
